
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {

        int mousepX;
        int mousepY;
        SignUp su;
        static String aioname;
        static String aiokey;
        public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        unamef = new javax.swing.JTextField();
        newuserslabel = new javax.swing.JLabel();
        pwdf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logincloselabel = new javax.swing.JLabel();
        submitbtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 400));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 98, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, 150));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("   All rights reserved                                       Copyright©_cloud_titans");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 380, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 193, 7));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, 40));

        unamef.setText("Username");
        unamef.setToolTipText("Username");
        unamef.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 98, 205))); // NOI18N
        unamef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unamefFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unamefFocusLost(evt);
            }
        });
        unamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unamefActionPerformed(evt);
            }
        });
        jPanel3.add(unamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, 40));

        newuserslabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        newuserslabel.setForeground(new java.awt.Color(255, 193, 7));
        newuserslabel.setText("Click Here");
        newuserslabel.setToolTipText("New user");
        newuserslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserslabelMouseClicked(evt);
            }
        });
        jPanel3.add(newuserslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 386, -1, 10));

        pwdf.setText("Password");
        pwdf.setToolTipText("Password");
        pwdf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pwdf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdfFocusLost(evt);
            }
        });
        pwdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdfActionPerformed(evt);
            }
        });
        jPanel3.add(pwdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 70));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 70));

        logincloselabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logincloselabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 1.png"))); // NOI18N
        logincloselabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logincloselabelMouseClicked(evt);
            }
        });
        jPanel3.add(logincloselabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 50, -1));

        submitbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rectangle 1.png"))); // NOI18N
        submitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitbtnMouseClicked(evt);
            }
        });
        jPanel3.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 50, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Submit");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Create new account ? ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 140, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon awesome-window-minimize.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 30, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 320, 400));

        setSize(new java.awt.Dimension(700, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int xcoo = evt.getXOnScreen();
        int ycoo = evt.getYOnScreen();
       // System.out.println(xcoo+"  "+ycoo);
      // this.setLocation(xcoo,ycoo);
       this.setLocation(xcoo-mousepX,ycoo-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void unamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unamefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unamefActionPerformed

    private void unamefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unamefFocusGained
       if(unamef.getText().equals("Username"))
       {
           unamef.setText("");
       }
    }//GEN-LAST:event_unamefFocusGained

    private void unamefFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unamefFocusLost
        if(unamef.getText().equals(""))
       {
           unamef.setText("Username");
       }
    }//GEN-LAST:event_unamefFocusLost

    private void pwdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdfActionPerformed

    private void pwdfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdfFocusGained
         if(pwdf.getText().equals("Password"))
       {
           pwdf.setText("");
       }
    }//GEN-LAST:event_pwdfFocusGained

    private void pwdfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdfFocusLost
         if(pwdf.getText().equals(""))
       {
           pwdf.setText("Password");
       }
    }//GEN-LAST:event_pwdfFocusLost

    private void newuserslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserslabelMouseClicked
            this.setVisible(false);
            try {
                su= new SignUp();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
             su.setVisible(true);
    }//GEN-LAST:event_newuserslabelMouseClicked

    private void logincloselabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logincloselabelMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_logincloselabelMouseClicked

    private void submitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitbtnMouseClicked
         String newuser = unamef.getText();
            String query = "select aiousername,aiokey,password from cloud where username=?";
            String password = null;
            try {
                Connectivity cons = Connectivity.getCon();
                cons.setQuery(query);
                ResultSet rs = cons.result(newuser);
                while(rs.next())
                {
                aioname=rs.getString("aiousername");
                aiokey=rs.getString("aiokey");
                password=rs.getString("password");
         
                }  rs.close();
        cons=null;
                  if(unamef.getText().equalsIgnoreCase(newuser) && pwdf.getText().equalsIgnoreCase(password)==true)
        {
            

          JOptionPane.showMessageDialog(null,"Successfully Logged in");
           
             this.setVisible(false);
             OptionHolder oh =new OptionHolder();
             oh.setVisible(true);
             oh.un.setText(newuser);
             oh.aun.setText(aioname);
             oh.akey.setText(aiokey);
             
      
           }
        else
        {
                       
           JOptionPane.showMessageDialog(null,"Incorrect password");
           //new OptionHolder().setVisible(true);
        }
                
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
      
    }//GEN-LAST:event_submitbtnMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        
          this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logincloselabel;
    private javax.swing.JLabel newuserslabel;
    private javax.swing.JPasswordField pwdf;
    private javax.swing.JLabel submitbtn;
    private javax.swing.JTextField unamef;
    // End of variables declaration//GEN-END:variables
}
