
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class SignUp extends javax.swing.JFrame {
        static Connectivity con;
        int mousepX;
        int mousepY;
         String query ="insert into cloud values(?,?,?,?,?)";
        public SignUp() throws SQLException, ClassNotFoundException {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signuplogopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        upperbackword = new javax.swing.JLabel();
        signuppanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        aiouname = new javax.swing.JTextField();
        aiokey = new javax.swing.JTextField();
        signupsubmitbtn = new javax.swing.JLabel();
        signupcloselabel = new javax.swing.JLabel();
        saiokey = new javax.swing.JLabel();
        snamel1 = new javax.swing.JLabel();
        smaillabel1 = new javax.swing.JLabel();
        smaillabel2 = new javax.swing.JLabel();
        smaillabel3 = new javax.swing.JLabel();
        backlabel = new javax.swing.JLabel();
        spwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 400));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signuplogopanel.setBackground(new java.awt.Color(0, 98, 205));
        signuplogopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 193, 7));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/round_person_add_white_36dp.png"))); // NOI18N
        signuplogopanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 60));

        upperbackword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upperbackword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon feather-arrow-left-circle.png"))); // NOI18N
        upperbackword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upperbackwordMouseClicked(evt);
            }
        });
        signuplogopanel.add(upperbackword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        getContentPane().add(signuplogopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 400));

        signuppanel.setBackground(new java.awt.Color(255, 255, 255));
        signuppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 193, 7));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign up");
        signuppanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 40));

        semail.setText("Email");
        semail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        semail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                semailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                semailFocusLost(evt);
            }
        });
        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });
        signuppanel.add(semail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 200, 40));

        sname.setText("Name");
        sname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                snameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                snameFocusLost(evt);
            }
        });
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        signuppanel.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 40));

        aiouname.setText("AIO_Username");
        aiouname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        aiouname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aiounameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aiounameFocusLost(evt);
            }
        });
        aiouname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiounameActionPerformed(evt);
            }
        });
        signuppanel.add(aiouname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, 40));

        aiokey.setText("AIO_Key");
        aiokey.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        aiokey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aiokeyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aiokeyFocusLost(evt);
            }
        });
        signuppanel.add(aiokey, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, 40));

        signupsubmitbtn.setBackground(new java.awt.Color(0, 98, 205));
        signupsubmitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rectangle 1.png"))); // NOI18N
        signupsubmitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupsubmitbtnMouseClicked(evt);
            }
        });
        signuppanel.add(signupsubmitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 40, -1));

        signupcloselabel.setForeground(new java.awt.Color(0, 0, 0));
        signupcloselabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupcloselabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 1.png"))); // NOI18N
        signupcloselabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupcloselabelMouseClicked(evt);
            }
        });
        signuppanel.add(signupcloselabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 0, 30, 30));

        saiokey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saiokey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pwd.png"))); // NOI18N
        saiokey.setToolTipText("");
        signuppanel.add(saiokey, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 40));

        snamel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snamel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/username.png"))); // NOI18N
        snamel1.setToolTipText("");
        signuppanel.add(snamel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, 40));

        smaillabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smaillabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        smaillabel1.setToolTipText("");
        signuppanel.add(smaillabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 40));

        smaillabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smaillabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/username_1.png"))); // NOI18N
        smaillabel2.setToolTipText("");
        signuppanel.add(smaillabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 40));

        smaillabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smaillabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        smaillabel3.setToolTipText("");
        signuppanel.add(smaillabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 40));

        backlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back arrow.png"))); // NOI18N
        backlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabelMouseClicked(evt);
            }
        });
        signuppanel.add(backlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        spwd.setText("Password");
        spwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spwdFocusLost(evt);
            }
        });
        signuppanel.add(spwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 200, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon awesome-window-minimize.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        signuppanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 30, 30));

        getContentPane().add(signuppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 330, 400));

        setSize(new java.awt.Dimension(704, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int xcoo = evt.getXOnScreen();
        int ycoo = evt.getYOnScreen();
       // System.out.println(xcoo+"  "+ycoo);
      // this.setLocation(xcoo,ycoo);
       this.setLocation(xcoo-mousepX,ycoo-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void signupsubmitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupsubmitbtnMouseClicked
            String name= sname.getText();
            String email=semail.getText();
            String pass=spwd.getText();
            String aiounames=aiouname.getText();
            String key=aiokey.getText();
           
           
            Geek g = Geek.getgeek(name, email, pass, aiounames, key);
          boolean b = false;
            try {
                  this.con=Connectivity.getCon();
          con.setQuery(query);
                b = con.insertData(g);
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
          if(b==true){
        JOptionPane.showMessageDialog(null,"Registered Successfully");
          }else{ JOptionPane.showMessageDialog(null,"unsupported inputs please input correctly");}
             this.setVisible(false);        
              new Login().setVisible(true);
    }//GEN-LAST:event_signupsubmitbtnMouseClicked

    private void signupcloselabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupcloselabelMouseClicked
      System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_signupcloselabelMouseClicked

    private void upperbackwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upperbackwordMouseClicked
       this.setVisible(false);
       new Login().setVisible(true);
       
    }//GEN-LAST:event_upperbackwordMouseClicked

    private void backlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseClicked
        this.setVisible(false);
       new Login().setVisible(true);
    }//GEN-LAST:event_backlabelMouseClicked

    private void snameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snameFocusGained
          if(sname.getText().equals("Name"))
       {
           sname.setText("");
       }
    }//GEN-LAST:event_snameFocusGained

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void snameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snameFocusLost
         if(sname.getText().equals(""))
       {
           sname.setText("Name");
       }
    }//GEN-LAST:event_snameFocusLost

    private void semailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semailFocusGained
        if(semail.getText().equals("Email"))
       {
           semail.setText("");
       }
    }//GEN-LAST:event_semailFocusGained

    private void semailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_semailFocusLost
         if(semail.getText().equals(""))
       {
           semail.setText("Email");
       }
    }//GEN-LAST:event_semailFocusLost

    private void spwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spwdFocusGained
         if(spwd.getText().equals("Password"))
       {
           spwd.setText("");
       }
    }//GEN-LAST:event_spwdFocusGained

    private void spwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spwdFocusLost
         if(spwd.getText().equals(""))
       {
           spwd.setText("Password");
       }
    }//GEN-LAST:event_spwdFocusLost

    private void aiounameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiounameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiounameActionPerformed

    private void aiounameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aiounameFocusGained
       
          if(aiouname.getText().equals("AIO_Username"))
       {
           aiouname.setText("");
       }
        
    }//GEN-LAST:event_aiounameFocusGained

    private void aiounameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aiounameFocusLost
        if(aiouname.getText().equals(""))
       {
           aiouname.setText("AIO_Username");
       }
        
    }//GEN-LAST:event_aiounameFocusLost

    private void aiokeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aiokeyFocusGained
          if(aiokey.getText().equals("AIO_Key"))
       {
           aiokey.setText("");
       }
    }//GEN-LAST:event_aiokeyFocusGained

    private void aiokeyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aiokeyFocusLost
         if(aiokey.getText().equals(""))
       {
           aiokey.setText("AIO_Key");
       }
    }//GEN-LAST:event_aiokeyFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aiokey;
    private javax.swing.JTextField aiouname;
    private javax.swing.JLabel backlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel saiokey;
    private javax.swing.JTextField semail;
    private javax.swing.JLabel signupcloselabel;
    private javax.swing.JPanel signuplogopanel;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JLabel signupsubmitbtn;
    private javax.swing.JLabel smaillabel1;
    private javax.swing.JLabel smaillabel2;
    private javax.swing.JLabel smaillabel3;
    private javax.swing.JTextField sname;
    private javax.swing.JLabel snamel1;
    private javax.swing.JPasswordField spwd;
    private javax.swing.JLabel upperbackword;
    // End of variables declaration//GEN-END:variables
}
